project:
  type: website

callout-icon: true
website:
  title: "KEPipedia"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Library
        href: blog/index.qmd

format:
  html:
    theme: 
      light: [flatly, assets/light.scss]
      dark: [darkly, assets/dark.scss]
    toc: true
